# Generated by Django 3.2.6 on 2021-08-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='hashtags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
